#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 tw=100 et ai si

"""
command line tool to send controller input over UDP.
"""

import sys
import argparse
from modules import UDP, Controller, Operator

VERSION = "0.1"
OWN_NAME = "remote-controller"

def parse_arguments():
    """A helper function which parses the input arguments."""

    text = sys.modules[__name__].__doc__
    parser = argparse.ArgumentParser(description=text, prog=OWN_NAME)

    text = "IP of the devise to send controls to."
    parser.add_argument("ip", metavar="IP", help=text)

    text = "Port on the devise to send controls to."
    parser.add_argument("port", metavar="PORT", help=text)

    text = "Controller device path."
    parser.add_argument("device", metavar="CONTROLLER", help=text)

    text = "Print version and exit."
    parser.add_argument("--version", action="version", help=text, version=VERSION)

    return parser.parse_args()

def main():
    """Script entry point after we gained the powerlab group."""

    args = parse_arguments()

    connection = UDP.UDP(args.ip, args.port)
    device = Controller.Controller(args.device)

    operator = Operator.Operator(connection, device)
    operator.run()

    return 0

# The script entry point.
if __name__ == "__main__":
    sys.exit(main())

